#!/bin/bash

# Function to start the process
start_process() {
    echo "manage_my_process started"
    (while true; do
        echo "I am alive!" >> /tmp/my_process
        sleep 2
    done) &
    echo $! > /var/run/my_process.pid
}

# Function to stop the process
stop_process() {
    if [ -f /var/run/my_process.pid ]; then
        echo "manage_my_process stopped"
        kill $(cat /var/run/my_process.pid)
        rm /var/run/my_process.pid
    else
        echo "manage_my_process is not running"
    fi
}

# Check for valid arguments
case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        stop_process
        start_process
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac

exit 0

