#!/bin/bash

# Set the input field separator to ":"
IFS=":"

# Read each line of the /etc/passwd file
while read -r username password uid gid user_info home shell; do
    # Display user information in the specified format
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd
